version: '3'

volumes:
  taski_pg_data:
    name: taski_pg_data
  taski_static_files:
    name: taski_static_files

# sudo docker volume create taski_pg_data && \
# sudo docker volume create taski_static_files

networks:
  taski_network:
    name: taski_network

# sudo docker network create taski_network

services:
  taski_db:
    image: postgres:13.10

    container_name: taski_db
    env_file: ./backend/.env
    networks:
      - taski_network
    volumes:
      - taski_pg_data:/var/lib/postgresql/data

# sudo docker pull postgres:13.10 && \
# sudo docker container run \
#     --name taski_db \
#     --env-file ./backend/.env
#     --volumes taski_pg_data:/var/lib/postgresql/data \
#     --net taski_network \
#     postgres:13.10

  taski_backend:
    image: deyvidasb/taski_backend:1.0

    depends_on:
      - taski_db

    container_name: taski_backend
    env_file: ./backend/.env
    networks:
      - taski_network
    volumes:
      - taski_static_files:/taski_backend_static

# sudo docker pull deyvidasb/taski_backend:1.0 && \
# sudo docker container run \
#     --name taski_backend \
#     --env-file ./backend/.env \
#     --volumes taski_static_files:/taski_backend_static \
#     --net taski_network \
#     deyvidass/taski_backend:latest

  taski_frontend:
    image: deyvidasb/taski_frontend:1.0

    container_name: taski_frontend
    env_file: ./backend/.env
    networks:
      - taski_network
    volumes:
      - taski_static_files:/taski_frontend_static

# sudo docker pull deyvidasb/taski_frontend:1.0 && \
# sudo docker container run \
#     --name taski_frontend \
#     --env-file ./backend/.env \
#     --volumes taski_static_files:/taski_frontend_static \
#     --net taski_network \
#     deyvidass/taski_frontend:latest

  taski_gateway:
    image: deyvidasb/taski_gateway:1.0

    depends_on:
      - taski_backend
      - taski_frontend

    container_name: taski_gateway
    networks:
      - taski_network
    ports:
      - 8000:80
    volumes:
      - taski_static_files:/taski_static

# sudo docker pull deyvidasb/taski_gateway:1.0 && \
# sudo docker container run \
#     --name taski_gateway \
#     --publish 8000:80 \
#     --volumes taski_static_files:/taski_static \
#     --net taski_network \
#     taski_gataway:latest