name: Main taski workflow

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Create and run psql container, check PEP8 and run tests
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: Set up Python3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      -
        name: Update pip and install dependency
        run: |
          pip install -U pip setuptools -r backend/requirements.txt
          pip install flake8==6.0.0 flake8-isort==6.0.0
      -
        name: Check PEP8 and run django tests
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          SEPARATOR: ", "
          DEBUG: False
          ALLOWED_HOSTS: "localhost, 127.0.0.1"
          CORS_ORIGIN_WHITELIST: http://localhost:3000
        run: |
          cd backend/
          flake8 .
          python manage.py test

  build_images_and_push_to_dockerhub:
    needs: run_tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Login to dockerhub, create docker images and push them

    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: Deploy Docker on workflow server
        uses: docker/setup-buildx-action@v2
      -
        name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHL }}
          password: ${{ secrets.DHP }}
      -
        name: Build and push created images on dockerhub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DHL }}/taski_backend:latest